language: node_js
node_js:
          - "6.*"
before_script:
          - npm install grunt-cli -g
          - npm install bower -g
          - npm install
script:
          - bower install
          # - grunt test
